Formatted alerts
sass/dart-sass-embedded pull request #35
Opened 2021-01-29 18:35 UTC by Awjin

Populates the formatted message field for exceptions and logs.

2021-02-03 22:11 UTC, nex3 requested changes

2021-02-03 22:11 UTC, nex3 commented on .gitignore
> +.DS_Store
Generally, OS-specific ignores should go in your computer-wide `.gitignore` rather than in each project.

2021-02-03 22:11 UTC, nex3 commented on lib/src/logger.dart
> +      formatted.writeln(' on ${span.message("\n" + message, color: _color)}');
It looks like these will produce Unicode messages even if `alertAscii` is set. Probably a good idea to add a test for that. You can use `a && b` to consistently produce a warning with a span that's unlikely to change in future Sass versions.

2021-02-03 22:11 UTC, nex3 commented on bin/dart_sass_embedded.dart
> +      term_glyph.ascii = globalAsciiConfig;
Consider adding a util function to make this clearer:

```dart
T withGlyphs<T>(T callback(), {@required bool ascii});
```

(Ideally this should be in `term_glyph` but you don't need to shave that yak if you don't want to.)

2021-02-03 22:59 UTC, Awjin commented on lib/src/logger.dart
> +      formatted.writeln(' on ${span.message("\n" + message, color: _color)}');
Good catch, thanks

2021-02-04 00:16 UTC, nex3 approved these changes
Looks great, thanks Awjin!

2021-02-04 00:16 UTC, nex3 commented on lib/src/logger.dart
> +    }
Style nit

```suggestion
    if (span != null) event.span = protofySpan(span);
```

2021-02-04 02:31 UTC, merged